Cadastro-Funcionarios-CRUD/CRUDMatrix/Models/BuscaCepModel.cs
using Microsoft.AspNetCore.Mvc;
namespace CRUDMatrix.Models
{
    public class BuscaCepModel
    {
        public string cep { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string neighborhood { get; set; }
        public string street { get; set; }
        public string service { get; set; }
    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Models/ClientesAPIModel.cs
using System;

namespace Cadastro_de_Funcionários.Models
{
    public class ClientesAPIModel
    {

        public int Id { get; set; }
        public string Nome { get; set; }
        public string cpf { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Sexo { get; set; }

        public string SituacaoClienteId { get; set; }







    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Models/Employee.cs
using Castle.MicroKernel.SubSystems.Conversion;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CRUDMatrix.Models
{
    public class Employee
    {
        
        [Key]
        public int EmployeeId { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required(ErrorMessage = "Campo obrigatório P#RRA!")]
        // Comando utilizado para Deixar o campo obrigatório ao salvar 
        [DisplayName("Nome Completo")]
   
        public string FullName { get; set; }


        [Column(TypeName = "nvarchar(50)")]
        [DisplayName("Matricula")]

        public int EmpCode { get; set; }
        [Column(TypeName = "nvarchar(100)")]
        [DisplayName("Cargo")]

        public string Position { get; set; }
        [Column(TypeName = "nvarchar(100)")]


        [DisplayName("Localização")]
        public string OfficeLocation { get; set; }


    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Models/EmployeeContext.cs
using Microsoft.EntityFrameworkCore;

namespace CRUDMatrix.Models
{
    public class EmployeeContext : DbContext
    {
        public EmployeeContext(DbContextOptions<EmployeeContext> options) : base(options)
        {

        }
        public DbSet<Employee> Employees { get; set; }

    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Models/ErrorViewModel.cs
using System;

namespace CRUDMatrix.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Models/Framework.cs
namespace Cadastro_de_Funcionários.Models
{
    public class Framework
    {
        public enum SituacaoCliente
        {
            Ativo = 1,
            Bloqueado = 2,
            Inativo = 3  
        }

    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Controllers/BuscaCepController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using CRUDMatrix.Models;

public class BuscaCepController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public BuscaCepController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    [HttpGet]
    public IActionResult BuscaCep()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> BuscaCep(string cep)
    {
        if (string.IsNullOrWhiteSpace(cep))
        {
            ModelState.AddModelError("", "Informe um CEP válido.");
            return View();
        }

        var client = _httpClientFactory.CreateClient();
        var response = await client.GetAsync($"https://brasilapi.com.br/api/cep/v1/{cep}");

        if (!response.IsSuccessStatusCode)
        {
            ModelState.AddModelError("", "CEP não encontrado.");
            return View();
        }

        var json = await response.Content.ReadAsStringAsync();
        var result = JsonConvert.DeserializeObject<BuscaCepModel>(json);

        return View(result);
    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Controllers/ClientesAPIController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Cadastro_de_Funcionários.Models;
using System.Net.Http;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace Cadastro_de_Funcionários.Controllers
{
    public class ClientesAPIController : Controller
    {
        public async Task<IActionResult> GetClienteAPI()
        {
            List<ClientesAPIModel> clientes = new List<ClientesAPIModel>();
            using (var httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync("https://localhost:7180/Cliente");
                if (response.IsSuccessStatusCode)
                {
                    var jsonString = await response.Content.ReadAsStringAsync();
                    clientes = JsonConvert.DeserializeObject<List<ClientesAPIModel>>(jsonString);
                }
            }
            return View(clientes);



        }
    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUDMatrix.Models;

namespace CRUDMatrix.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly EmployeeContext _context;

        public EmployeesController(EmployeeContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

      

        // GET: Employees/Create
        public IActionResult AddOrEdit(int id=0)
        {
            if(id == 0)
            return View(new Employee());
            else
                return View(_context.Employees.Find(id));
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("EmployeeId,FullName,EmpCode,Position,OfficeLocation")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                if (employee.EmployeeId == 0)
                    _context.Add(employee);
                   else
                    _context.Update(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

      

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

      
      
    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Controllers/HomeController.cs
using CRUDMatrix.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CRUDMatrix.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Views/BuscaCep/BuscaCep.cshtml
@model CRUDMatrix.Models.BuscaCepModel

<form asp-action="BuscaCep" method="post">
    <input type="text" name="cep" placeholder="Digite o CEP" value="@Model?.cep" />
    <button type="submit">Buscar</button>
</form>

@if (Model != null && !string.IsNullOrEmpty(Model.cep))
{
    <div>
        <p><strong>CEP:</strong> @Model.cep</p>
        <p><strong>Estado:</strong> @Model.state</p>
        <p><strong>Cidade:</strong> @Model.city</p>
        <p><strong>Bairro:</strong> @Model.neighborhood</p>
        <p><strong>Rua:</strong> @Model.street</p>
        <p><strong>Serviço:</strong> @Model.service</p>
    </div>
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Views/ClientesAPI/GetClienteAPI.cshtml
@model IEnumerable<Cadastro_de_Funcionários.Models.ClientesAPIModel>
@using Cadastro_de_Funcionários.Models




<h2>Clientes da API</h2>
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Data de Nascimento</th>
            <th>Sexo</th>
            <th>Situação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cliente in Model)
        {
            <tr>
                <td>@cliente.Nome</td>
                <td>@cliente.cpf</td>
                <td>@cliente.DataNascimento.ToShortDateString()</td>
                <td>@cliente.Sexo</td>
                <td>@cliente.SituacaoClienteId</td>
                <td>@(Enum.TryParse(typeof(Framework.SituacaoCliente), cliente.SituacaoClienteId, out var situacao) ? (Framework.SituacaoCliente)situacao : (Framework.SituacaoCliente)0)</td>

            </tr>
        }
    </tbody>
</table>

Cadastro-Funcionarios-CRUD/CRUDMatrix/Views/Employees/AddOrEdit.cshtml
@model CRUDMatrix.Models.Employee

@{
    ViewData["Title"] = "Cadastro";
}

<style>
    .cadastro {
        text-align: left;
    }

        .cadastro img {
            border-radius: 20px;
        }
</style>

<div class="cadastro">
    <img src="/css/Cadastro.gif" alt="Descrição da Imagem" width="400" height="80">
   
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddOrEdit"> 
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmployeeId" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>

            <div class="row">


            <div class="form-group col-md-6">
                <label asp-for="EmpCode" class="control-label"></label>
                <input asp-for="EmpCode" class="form-control" />
                <span asp-validation-for="EmpCode" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>

            </div>
            <div class="form-group">
                <label asp-for="OfficeLocation" class="control-label"></label>
                <input asp-for="OfficeLocation" class="form-control" />
                <span asp-validation-for="OfficeLocation" class="text-danger"></span>
            </div>

             <div class="row"  >
            <div class="form-group col-md-6">
                <input type="submit" value="Salvar" class="btn btn-primary btn-block" />
            </div>

            <div  class="form-group col-md-6" >
                     <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Voltar </a>
            </div>

            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cadastro-Funcionarios-CRUD/CRUDMatrix/Views/Employees/Index.cshtml
@model IEnumerable<CRUDMatrix.Models.Employee>

@{
    ViewData["Title"] = "Funcionários";
}
<style>
    .funcionario {
        text-align: left;
    }

        .funcionario img {
            border-radius: 20px;
        }
</style>

<div class="funcionario">
    <img src="/css/Funcionários.gif" alt="Descrição da Imagem" width="200" height="50">
   
</div>



<p>
   
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmpCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficeLocation)
            </th>
            <th>
                 <a asp-action="AddOrEdit" class="btn btn-outline-success"><i class="far fa-plus-square"></i>Novo</a>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmpCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficeLocation)
            </td>
            <td>
                <a asp-action="AddOrEdit" asp-route-id="@item.EmployeeId" ><i class="fa fa-marker fa-lg"></i></a> |
              
                <a asp-action="Delete" asp-route-id="@item.EmployeeId" onclick="return confirm('Deseja Excluir?')" class="text-danger"><i class="fa fa-trash-alt fa lg"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

Cadastro-Funcionarios-CRUD/CRUDMatrix/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div  class="text-center">
    <img src="/css/SISTEMA DE CADASTRO DE CLIENTES.gif" alt="Descrição da Imagem" width="1000" height="200">
    
</div>

<style>
    .text-center {
        text-align: center;
    }

        .text-center img {
            border-radius: 25px;
        }

        .body{
            background-color:gray;
        }
</style>

Cadastro-Funcionarios-CRUD/CRUDMatrix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Cadastro de Funcionários</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    <style>
        .body{
            background-color:lightslategray;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info border-bottom box-shadow mb-3">
            <div class="container">
             
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">

                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-dark">
                     <svg xmlns="http://www.w3.org/2000/svg"  width="20" height="20" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                        <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5"/>
                         </svg>
    
                            </a>

                        </li>
                        @* CABEÇALHO HEADER  *@
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClientesAPI" asp-action="GetClienteAPI">API Integração</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BuscaCep" asp-action="BuscaCep">Consulta CEP</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
          
            Sistema de Cadastro  <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>